implemented different image list loading by piece data and example fo…
redaxtor/redaxtor-medium pull request #9
Opened 2017-02-24 10:28 UTC by aleksey-alifer

…r it

2017-02-24 16:37 UTC, AndrewKirkovski requested changes

2017-02-24 16:37 UTC, AndrewKirkovski commented on src/BackgroundImageEditor.js
> +            pieceData: {
please rename it to pieceRef and add "dataset" to data passed
dataset is user-specified data and may be usefull in abstract scenario

2017-02-24 16:37 UTC, AndrewKirkovski commented on src/ImageTagEditor.js
> +            pieceData: {
please rename it to pieceRef and add "dataset" to data passed
dataset is user-specified data and may be usefull in abstract scenario

2017-02-24 16:37 UTC, AndrewKirkovski commented on src/imageManager/ImageManager.js
> +        if(data.pieceData){
on what condition we don't have pieceData here? We should always have it, even from rich text image inserting.
b.t.w. rich text image insert functionality is not passing it currently, but it should. Add it there too

2017-02-27 10:22 UTC, aleksey-alifer commented on src/BackgroundImageEditor.js
> +            pieceData: {
done

2017-02-27 10:22 UTC, aleksey-alifer commented on src/ImageTagEditor.js
> +            pieceData: {
done

2017-02-27 10:23 UTC, aleksey-alifer commented on src/imageManager/ImageManager.js
> +        if(data.pieceData){
we've disscued it on the skype. It done

2017-02-28 13:27 UTC, merged